[tool]
[tool.poetry]
name = "MerlinUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy MerlinUserBot to Heroku"
authors = ["Yusuf Usta <yusuf@quiec.tech>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
